package com.example.demo.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainPage extends HorizontalLayout {
	protected CssLayout mainlayout;
	protected HorizontalLayout menuTitle;
	protected Label menuTitleLabel;
	protected Image img;
	protected Button menuToggle;
	protected CssLayout menuItems;
	protected Button student;
	protected Button gatepass;
	protected Button logout;
	protected VerticalLayout mainpagevl;
	protected Label mainlabel;
	protected VerticalLayout content;

	public MainPage() {
		Design.read(this);
	}
}
